#!/bin/sh

set -eux

# Prerequisites
env ASSUME_ALWAYS_YES=YES pkg bootstrap
pkg install -y ca_root_nss

# Install Salt
fetch -o /tmp/install_salt.sh https://bootstrap.saltstack.com
chmod +x /tmp/install_salt.sh
/tmp/install_salt.sh -X -P git v2015.8.3

# When install salt with git option a minion config is created rather than a
# minion.sample.  Check for it and backup before writing own.
[ -f /usr/local/etc/salt/minion ] && \
  cp /usr/local/etc/salt/minion /usr/local/etc/salt/minion.orig

# Create minion config
cat << EOF > /usr/local/etc/salt/minion
file_client: local
file_roots:
  base:
    - /usr/local/etc/salt
    - /usr/local/etc/salt/states

pillar_roots:
  base:
    /usr/local/etc/salt/pillar
EOF

# Create Salt dirs, script will bail if these are already present.
mkdir /usr/local/etc/salt/{states,pillar}

# Fetch tarball of Salt state repo and copy into correct locations.  The
# project is organised a little odd due to kitchen-salt, just copy what is
# needed rather than everything.
fetch -o /tmp/salt-rosstimson.tar.gz \
  https://github.com/rosstimson/salt-rosstimson/archive/master.tar.gz
tar xzvf /tmp/salt-rosstimson.tar.gz

cp -r /tmp/salt-rosstimson-master/{base,wifi,rosstimson,tools} \
  /usr/local/etc/salt/states

# Begin provsioning via Salt.
salt-call --local state.highstate

